apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: the-library
spec:
  type: NodePort
  selector:
    app: mongodb
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 27017
      targetPort: 27017