name: Release

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    name: Deploy to OpenShift
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Buildah Action
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: |
            ./Dockerfile
          image: the-library
          tags: latest ${{ github.sha }}

      - name: Push To quay.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/dyego_maas
          username: dyego_maas
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Install CLI tools from OpenShift Mirror
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: "3"

      - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1
        env:
          OPENSHIFT_USER: ${{ secrets.OPENSHIFT_USER }}
          OPENSHIFT_NAMESPACE: ${{ env.OPENSHIFT_NAMESPACE }}

        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: false
          namespace: ${{ env.OPENSHIFT_NAMESPACE }} 
 
      - name: Deploy to OpenShift
        run: |
          oc apply -R -f ./k8s