name: CreateMongoDb

on: 
  workflow_dispatch:

jobs:
  release:
    name: Deploy to OpenShift
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
    
      - name: Install CLI tools from OpenShift Mirror
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: "3"

      - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1
        env:
          # These can be stored in secrets, if desired.
          OPENSHIFT_USER: ${{ secrets.OPENSHIFT_USER }}
          OPENSHIFT_NAMESPACE: ${{ env.OPENSHIFT_NAMESPACE }}

        with:
          # URL to your OpenShift cluster.
          # Refer to Step 2.
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}

          # Authentication Token. Can use username and password instead.
          # Refer to Step 3.
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          # Credentials, if desired instead of token.
          # Username and password override token if they are set.
          # openshift_username: ${{ secrets.OPENSHIFT_USER }}
          # openshift_password: ${{ secrets.OPENSHIFT_PASSWORD }}

          # Disables SSL cert checking. Use this if you don't have the certificate authority data.
          insecure_skip_tls_verify: false
          # This method is more secure, if the certificate from Step 4 is available.
          # certificate_authority_data: ${{ secrets.CA_DATA }}

          # Optional - this sets your Kubernetes context's current namespace after logging in.
          namespace: ${{ env.OPENSHIFT_NAMESPACE }} 
        
      - name: Create MongoDB
        run: |
          oc new-app -e MONGODB_USER=${{ secrets.MONGO_USER }} -e MONGODB_PASSWORD=${{ secrets.MONGO_PASSWORD }} -e MONGODB_DATABASE=${{ secrets.MONGO_DATABASE }} -e MONGODB_ADMIN_PASSWORD=${{ secrets.MONGO_ADMIN_PASSWORD }} registry.redhat.io/rhscl/mongodb-36-rhel7 --name mongodb